### ISSUE TITLE
When shuffle is true, and there is only 1 song in the list, the game hangs

### ISSUE THREAD

**Issue by eternalflamez** [Zesix/Impulse#2]
I propose changing

```
while (newTrack == _counter)
```

to

```
while (newTrack == _counter && Playlist.MusicList.Length != 1)
```

In MusicManager.cs. Otherwise the thread will get stuck in that while loop forever, causing Unity or the standalone game to hang.

**Comment by Zesix** [comment]
Thanks for the issue! It has been fixed in the latest commit.
